name: Outdated

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  outdated:
    name: Check outdated
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: 22.1
          elixir-version: 1.9.4

      - name: Check outdated certdata
        run: |
          mix deps.get
          mix compile
          .github/workflows/outdated.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
